### ISSUE TITLE
Opencore

### ISSUE THREAD

**Issue by sebasinparis** [dreamwhite/dell-inspiron-5370-hackintosh#1]
Hi, this is not an issue, it's just the only way I could find for us to communicate. Do you ever think about moving your EFI over to opencore? It's an upgrade over clover for those who manage. I have the same computer and have been trying for months now and had to accept that I'm simply inept at it. Btw thanks for your headphone fix! I've had this hack for two years now and never got it to work before stumbling into your GitHub. Thanks

**Comment by mammamiamarcello** [comment]
Sorry for late reply. Well, I've tried using opencore but due to continuously updates by the team I think I'll migrate to it when it will be stable. Opencore also is a lot stressing and you need to meditate with your self without breaking your PC 😂

**Comment by dreamwhite** [comment]
Close issue

**Comment by sebasinparis** [comment]
I haven’t signed in in a while, apologies for the late reply. Going through the commits, I see that you’ve been keeping busy during the quarantine lol. Since you’re currently preparing to migrate to OpenCore, I’m more than willing to help with the testing. Thanks again.

**Comment by dreamwhite** [comment]
> I’m more than willing to help with the testing

I need to test it more, but currently everything's working smooth 😍

**Comment by sebasinparis** [comment]
I was scrolling through your setup & it seems you don't have the brightness keys working natively. Maybe I misread things, if so; feel free to delete my comment.
Apply the patches from this config along with the aml files. Remove everything regarding brightness from your OpenCore including your SSDT-PS2K.aml & I promise you'll be able to use your F11-F12 keys like windows. I hope I was able to help you this time lol.
[Archive.zip](https://github.com/dreamwhite/dell-inspiron-5370-hackintosh/files/5584982/Archive.zip)

**Comment by dreamwhite** [comment]
> I was scrolling through your setup & it seems you don't have the brightness keys working natively. Maybe I misread things, if so; feel free to delete my comment.
> Apply the patches from this config along with the aml files. Remove everything regarding brightness from your OpenCore including your SSDT-PS2K.aml & I promise you'll be able to use your F11-F12 keys like windows. I hope I was able to help you this time lol.
> [Archive.zip](https://github.com/dreamwhite/dell-inspiron-5370-hackintosh/files/5584982/Archive.zip)

Thank you for your advice but my laptop doesn't have a backlit keyboard neither a ALS, so the patches you provided are pretty unnecessary :/ 

Same applies for SSDT-XOSI which can easily break ACPI parts

**Comment by sebasinparis** [comment]
Oh ok. Interesting info about XOSI, I'll look into it
