### ISSUE TITLE
Does it support the AMD Radeon 530 Discrete GPU Model?

### ISSUE THREAD

**Issue by devadattas** [dreamwhite/dell-inspiron-5370-hackintosh#18]
Does it support the AMD Radeon 530 Discrete GPU Model? If not, what modifications do we have to make to get it working?

**Comment by dreamwhite** [comment]
AMD discrete GPUs on laptops aren't supposed to work due to MUX technology which isn't compatible with macOS.
Also, supposing that the GPU worked, you would probably have sleep/wake issues
