### ISSUE TITLE
could you test this headphone solution

### ISSUE THREAD

**Issue by shm007g** [dreamwhite/dell-inspiron-5370-hackintosh#2]
I've found this headphone solution work for my t450. 
You can test it! 

https://github.com/EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi

If you add this to your startup load apps, it works all time.

**Comment by mammamiamarcello** [comment]
Yeah k know it but I didn't added "my fix" inside startup load apps. It's a system job, such as a Linux cron job. No worries haha

**Comment by shm007g** [comment]
Did you test this fix or not? Did it works or not? @mammamiamarcello

**Comment by mammamiamarcello** [comment]
Yeah but I prefer more having a daemon than having a startup script :yum:

**Comment by dreamwhite** [comment]
Closed issue
