### ISSUE TITLE
Sometime keyboard and touchpad are no working.

### ISSUE THREAD

**Issue by yimwhancafe** [dreamwhite/dell-inspiron-5370-hackintosh#3]
Hello 

I use dell inspiron-5370 cpu i7. sometime keyboard and touchpad are no working.
solve basic problems use sleep or restart my laptop.

**Comment by dreamwhite** [comment]
Have you updated kexts? What's your CPU generation?
If it's CFL add this bootarg: `ps2rst=0`. For Trackpad I don't know. Try filling a bug report on VoodooI2C repository

**Comment by yimwhancafe** [comment]
My CPU Core i7-8550U. I try add bootarg: ps2rst=0 and test sleep and restart. No problems found.

Thank you.
