### ISSUE TITLE
2020.06 update planning

### ISSUE THREAD

**Issue by dreamwhite** [dreamwhite/dell-inspiron-5370-hackintosh#4]
Preparing for migration to OpenCore 0.5.8
Many thanks to @marianopela and @1alessandro1 which helped me

Working:

- Audio (working also via HDMI, DP and even with BT)
- 3.5 mm combojack (only audio)
- Microphone (only internal working)
- Graphics (brightness control + fn keys)
- USB mapping
- MicroSD Card Reader (which relies on USB bus)
- Trackpad (with gestures, requires only SSDT-XOSI + "_OSI to XOSI" rename)
- WiFi/BT (DW1830 native WiFi card)

**Comment by dreamwhite** [comment]
Due to @acidanthera new releases planned for today, I'll wait for them and update the EFI. Stay tuned!

**Comment by dreamwhite** [comment]
Successfully updated to OpenCore 0.5.9

**Comment by yimwhancafe** [comment]
Hello 

I use OpenCore 0.5.9 keyboard and touchpad are no working on boot. Where should the problem begin to be investigated?

Dell Inspiron 5370  i7-8550U.
Thank in advance
