### ISSUE TITLE
[USB Mapping] Webcam stops working after sleep

### ISSUE THREAD

**Issue by dreamwhite** [dreamwhite/dell-inspiron-5370-hackintosh#5]
I'm opening this issue to keep an eye on this strange bug: after some (still need to figure out how many) sleep/wake cycles the internal webcam stops working, despite the IORegistry device tree for USB is untouched. 

To fix you must reboot the machine and that's not the best idea in the world in my opinion.

Probably this problem is caused by the current port type definition in `SSDT-3-xh_OEMBD` as depicted below:

![image](https://user-images.githubusercontent.com/17933708/123909882-f6cf8f00-d979-11eb-9e49-658da81a7483.png)

I'll make some tests by changing the port type definition from `0xFF` to `0x00` and see if this problem is fixed or not

**Comment by dreamwhite** [comment]
Useful resources to give a read:

- [https://github.com/dortania/bugtracker/issues/166#issuecomment-792072852](khronokernel's USB 0xFF explanation)

**Comment by Mateo1234454545** [comment]
So, did you run the tests?
Would be better with 0x00?

**Comment by dreamwhite** [comment]
> So, did you run the tests?
> Would be better with 0x00?

I did some tests with the webcam USB port capability set to `0xFF` and was able to reproduce the bug just 3/10 times.
I suggest to change the USB connector to `0x00` as it seems more solid. Probably this is related due to the 0xFF hot-plug stuff which interferes with the nature of the webcam port itself
