### ISSUE TITLE
igpu stays at 0.30GHz

### ISSUE THREAD

**Issue by Mateo1234454545** [dreamwhite/dell-inspiron-5370-hackintosh#6]
Not really an issue but...

Have you experienced this problem  :

watch a 4k video or something stressful for igpu (like after a zoom meeting for example)
then sleep
and wake up
igpu stays at 0.30 until next reboot?

**Comment by dreamwhite** [comment]
> Not really an issue but...
> 
> Have you experienced this problem :
> 
> watch a 4k video or something stressful for igpu (like after a zoom meeting for example)
> then sleep
> and wake up
> igpu stays at 0.30 until next reboot?

Well to be fair I tried reproducing a 4K video on YouTube and I get laggy frames. I'm going to download it and report it in a while

**Comment by dreamwhite** [comment]
Update: definitely not. I monitored the iGPU frequency while playing back a 4K video downloaded from YouTube and watched it for 5 minutes. The iGPU frequency reached about 1.1GHz which is pretty normal considered that is a UHD620 with a peak frequency of 1.1GHz.

After closing the playback of the video, I tested with Intel Power Gadget the Intel iGPU Maximum Frequency and again, it raised up to 1.1GHz.
I don't know why you're experiencing this kind of issue and how you did the tests...

P.S. can you gently attach your iGPU patch?

**Comment by Mateo1234454545** [comment]
I tried several igpu patches , yours too , but the problem remains.
After watching a 4k video or zoom meeting , you have to put the laptop to sleep and then wake up. Then the igpu stays at 0.3.
Doesn't happen all the time and I don't know what triggers  it.
[Screen Shot 2021-07-02 at 00.13.13.pdf](https://github.com/dreamwhite/dell-inspiron-5370-hackintosh/files/6750818/Screen.Shot.2021-07-02.at.00.13.13.pdf)

**Comment by dreamwhite** [comment]
> I tried several igpu patches , yours too , but the problem remains.
> After watching a 4k video or zoom meeting , you have to put the laptop to sleep and then wake up. Then the igpu stays at 0.3.
> Doesn't happen all the time and I don't know what triggers  it.
> [Screen Shot 2021-07-02 at 00.13.13.pdf](https://github.com/dreamwhite/dell-inspiron-5370-hackintosh/files/6750818/Screen.Shot.2021-07-02.at.00.13.13.pdf)
> 

Try using my iGPU patch (after double checking the connector patches) and report back :/

**Comment by Mateo1234454545** [comment]
As I said in my previous post i did. The problem was there also.
There was a bugtracker issue at whatevergreen.kext about this issue , but I can't find it now.

**Comment by dreamwhite** [comment]
> As I said in my previous post i did. The problem was there also.
> There was a bugtracker issue at whatevergreen.kext about this issue , but I can't find it now.

I can't help you fixing this issue sorry. On my side I don't such problem. I'm leaving the issue opened for those who can help.
Sorry

**Comment by dreamwhite** [comment]
Little update: I tried exporting in H.264 a video with FCPX and noticed that for a while the CPU frequency stucked at 900MHz then raised up to 2.7GHz (as usual). I can't find a way to reproduce the bug but from what I remember I started rendering the video after waking the laptop from ACPI S3 mode 😅.
Can you gently make your tests and report back?
Many thanks
