### ISSUE TITLE
No boot option on last release

### ISSUE THREAD

**Issue by Sim7b** [dreamwhite/dell-inspiron-5370-hackintosh#6]
Hello,
Thanks for your work, I use your build since few months.
With the latest build, I have no boot option on OpenCore.
Only : 
* modGRUBShell.efi
* Openshell.efi
* VerifyMsrE2.efi
* Reset NVRAM
I have 2 systems before MacOS and Windows.
Thanks !

**Comment by dreamwhite** [comment]
Hi, have you tried setting ScanPolicy to 0? Please let me know :)

**Comment by Sim7b** [comment]
Ok, now I see Only "EFI" and "MacOS". But MacOS won't boot.

**Comment by dreamwhite** [comment]
Have you modded your BIOS with modGRUBShell.efi? Look for DVMT :)

**Comment by dreamwhite** [comment]
Have you modded your BIOS with modGRUBShell.efi? Look for DVMT :)
