### ISSUE TITLE
First Boot 

### ISSUE THREAD

**Issue by ted34** [dreamwhite/dell-inspiron-5370-hackintosh#7]
Hi , i Had before Catalina without Problems with your EFI . Now i want to Install BigSur(latest) with your latest EFI but in the first Boot it makes a restart and after that it comes and freezes.  On which Bios Version are you ? İ really Need Bug sur on the laptop , since tree days i am trying to her it work but no possibility .

**Comment by ted34** [comment]
![Uploading 100093870...]

**Comment by ted34** [comment]
![image](https://user-images.githubusercontent.com/23086945/100093931-83502700-2e58-11eb-9ea5-2b71bd130978.jpeg)

**Comment by ted34** [comment]
I have already disabled the keyboard backlight .

**Comment by dreamwhite** [comment]
> Hi , i Had before Catalina without Problems with your EFI . Now i want to Install BigSur(latest) with your latest EFI but in the first Boot it makes a restart and after that it comes and freezes. On which Bios Version are you ? İ really Need Bug sur on the laptop , since tree days i am trying to her it work but no possibility .

Hi, I'm using the latest version of BIOS and I'm using Big Sur with the latest EFI provided on this repo (use the last commit)

**Comment by ted34** [comment]
So i have tried to make a clean install with catalina and the efi from 3.August 0.6.0 I get it to work . But with Big Sur no chance to get the installer open with your latest 0.6.3 . Do you have any option to get it work ?

**Comment by dreamwhite** [comment]
> So i have tried to make a clean install with catalina and the efi from 3.August 0.6.0 I get it to work . But with Big Sur no chance to get the installer open with your latest 0.6.3 . Do you have any option to get it work ?
> 
> I also have the cfg unlock efi opend and have reset the nvram ...

I can confirm that I'm on latest bios version and big sur works flawlessly. I've updated directly from macOS Catalina 10.15.7 to Big Sur 11.0.1 and everything is working smooth ^^>

**Comment by dreamwhite** [comment]
@ted34 can you gently confirm me that using OC 0.6.4 from my repository you can boot? Thx

**Comment by ted34** [comment]
Im sorry , I can't confirm . It's not working for me

**Comment by dreamwhite** [comment]
Where are you stucked on?

**Comment by dreamwhite** [comment]
> Im sorry , I can't confirm . It's not working for me

Can you please download macOS Recovery using macrecovery.py? For more infos check out this [procedure](https://dortania.github.io/OpenCore-Install-Guide/installer-guide/winblows-install.html#downloading-macos)

**Comment by ted34** [comment]
> > Im sorry , I can't confirm . It's not working for me
> 
> Can you please download macOS Recovery using macrecovery.py? For more infos check out this [procedure](https://dortania.github.io/OpenCore-Install-Guide/installer-guide/winblows-install.html#downloading-macos)

Thanks , will try at Weekend

**Comment by dreamwhite** [comment]
@ted34 good morning and happy new year ^^ 
Do you have any news about booting macOS using OpenCore?

**Comment by dreamwhite** [comment]
sorry for rushing this a bit, but have you tried it yet?
